class_name Ability
extends Node

@export var interval: int = 1000

# Modifiers that affect the ability itself
var attached_modifiers: Array[Modifier] = []

# Modifiers that affect the damager(s) generated by the ability.
# Behaves like a singleton, so don't use if your modifier requires state.
var attached_damager_modifiers: Array[Modifier] = []

# Like the damager modifiers, but should be called to generate a stateful
# modifier.
var attached_damager_callables: Array[Callable] = []

var elapsed: int = 0
var activated: bool = false


func activate(_user: Actor, _spawn_marker: Marker2D) -> void:
	if activated:
		return
	else:
		on_activated()
		_internal_activate(_user, _spawn_marker)
		on_deactivated()


func _internal_activate(_user: Actor, _spawn_marker: Marker2D) -> void:
	pass


func on_activated() -> void:
	activated = true


func on_deactivated() -> void:
	elapsed = 0
	activated = false

